#!/bin/bash
#Easier to apply patches


if [ "$1" == "" ]
then
	echo "Please provide a patch URL"
	exit -1
fi

patch=$1

if [[ "$1" != "*.patch" ]]
then
	patch="$1.patch"
fi

if [ -e /tmp/p.patch ] 
then
	rm /tmp/p.patch 
fi

wget --quiet -r $patch -O /tmp/p.patch 

if [ ! -e /tmp/p.patch  -o $? != 0 ]
then
	echo "There was a problem downloading the patch"
	exit -2
fi

patch_title=$(cat /tmp/p.patch | grep Subject: | cut -d':' -f2-)
echo "Tying to apply patch: $patch_title"
git apply --check /tmp/p.patch 2>/dev/null

if [ $? != 0 ] 
then
	echo "The patch can't be applied"
	exit -3
else
	git am --signoff < /tmp/p.patch
	if [ $? != 0 ]
	then
		echo "There was an error applying the patch"
		exit -4
	else
		rm /tmp/p.patch
		echo "Patch applied succesfully"
	fi
fi

exit 0

