#!/bin/bash

if [ ! -e kappa.config ]
then   
        echo "Please create a kappa.config file in the repo dir."
        echo "Check kappa.config.sample for pointers"
        exit -1
fi

source kappa.config

echo "Making them all"
cd $KAPPA_HOME

echo "Applying Mango defconfig"
mkdef mango
echo "Making Mango"
mkbuild mango

echo "Applying Coconut defconfig"
mkdef coconut
echo "Making Coconut"
mkbuild coconut

echo "Applying Satsuma defconfig"
mkdef satsuma
echo "Making Satsuma"
mkbuild satsuma

echo "Applying Smultron defconfig"
mkdef smultron
echo "Making Smultron"
mkbuild smultron

echo "Done, I'll get some rest now"


