#!/bin/bash

echo "Making them all"
cd $KAPPA_HOME

echo "Applying Mango defconfig"
mkdef mango
echo "Making Mango"
mkbuild mango


echo "Applying Coconut defconfig"
mkdef coconut
echo "Making Coconut"
mkbuild coconut

echo "Applying Satsuma defconfig"
mkdef satsuma
echo "Making Satsuma"
mkbuild satsuma

echo "Applying Smultron defconfig"
mkdef smultron
echo "Making Smultron"
mkbuild smultron

echo "Done, I'll get some rest now"


