#!/bin/bash

if [ ! -e kappa.config ]
then
	echo "Please create a kappa.config file in the repo dir."
	echo "Check kappa.config.sample for pointers"
	exit -1
fi  

source kappa.config

if [ "$1" == "" ]
then   
        echo "Please provide the device name"
        echo "Valid devices: smultron mango satsuma coconut"
        exit -1
fi


echo "Building Kappa Kernel for ${1^}"
echo "Using Toolchain: $KAPPA_COMPILER"
echo "--------------------------------"
echo ""

if [ -e configs/current_config ]
then
	echo "Checking configuration consistency with requested build"
	CURRENT_CONFIG=`(cat configs/current_config)`
	if [  $CURRENT_CONFIG != "ka_$1_defconfig" ]
	then
		echo "Configured for another device than requested build."
		echo "Stop"
		exit -1
	else
		echo "Checking .config against default device config"
		cmp .config configs/ka_$1_defconfig > /dev/null
		if [ $? -eq 1 ]
		then
			echo "Current build config different from default device config."
			echo "This is an experimental build"
		else
			echo "Current build config matches default device config. Safe to proceed"
		fi
	fi
fi


export KAREL=`(cat configs/release)`

BUILD_FILE=$KAPPA_HOME/configs/$1_build.txt
if [ ! -e $BUILD_FILE ]; 
then
	echo "0" > $BUILD_FILE
fi

cd $KAPPA_HOME
CONFIG_CC_OPTIMIZE_ALOT=y ARCH=arm CROSS_COMPILE=$KAPPA_COMPILER  make -j8 
#CONFIG_CC_OPTIMIZE_ALOT=y ARCH=arm CROSS_COMPILE=$KAPPA_COMPILER  make -j8 modules

if [ $? == 0 ]
then
	if [ -e ramdisk/rek/build ]
	then
		rm ramdisk/rek/build
	fi
	echo $KAREL-$((`cat $BUILD_FILE` + 1)) > ramdisk/rek/build
	echo $((`cat $BUILD_FILE` + 1)) > $BUILD_FILE
	BUILD_NUMBER=$[`cat $BUILD_FILE`]

	mkimg Ka${1^}$BUILD_NUMBER.img
	if [ -e bootimg/Ka${1^}$BUILD_NUMBER.img ]
	then
		rm release/Ka${1^}*
		cp $(ls bootimg/Ka${1^}*.img -1t | head -1) release/
	else
		echo "Build failed"
		exit -1
	fi
	echo "Done!"
	exit 0
else
	echo "Error in kernel compilation: halting"
	exit -1
fi

