#!/bin/bash

if [ ! -e kappa.config ]
then                                                                                                                                   
        echo "Please create a kappa.config file in the repo dir."
        echo "Check kappa.config.sample for pointers"                                                                                  
        exit                                                                                                                           
fi                                                                                                                                     

source kappa.config                                                                                                                 


echo "Prepping Kernel image $1"
cd $KAPPA_HOME

echo "Removing old modules from Ramdisk tree"
rm -fr $KAPPA_HOME/ramdisk/system/lib/*.ko
rm -fr $KAPPA_HOME/ramdisk/rek/modules/*.ko

echo "Copying Kernel drivers into Ramdisk (/system/lib)"
find . -name *.ko | grep -v compat-wireless-wl12xx | grep -v ramdisk 
find . -name *.ko | grep -v compat-wireless-wl12xx | grep  -v ramdisk | xargs -i cp {} $KAPPA_HOME/ramdisk/system/lib/ 
mv $KAPPA_HOME/ramdisk/system/lib/cifs.ko $KAPPA_HOME/ramdisk/rek/modules/
mv $KAPPA_HOME/ramdisk/system/lib/ntfs.ko $KAPPA_HOME/ramdisk/rek/modules/
mv $KAPPA_HOME/ramdisk/system/lib/fuse.ko $KAPPA_HOME/ramdisk/rek/modules/
mv $KAPPA_HOME/ramdisk/system/lib/hfsplus.ko $KAPPA_HOME/ramdisk/rek/modules/
mv $KAPPA_HOME/ramdisk/system/lib/usb-storage.ko $KAPPA_HOME/ramdisk/rek/modules/

echo "Copying Wifi drivers into Ramdisk (/rek/modules)"
cd $KAPPA_HOME/net/compat-wireless/drivers/net/wireless/
find . -name wl12xx*.ko
find . -name wl12xx*.ko | xargs -i cp {} $KAPPA_HOME/ramdisk/rek/modules/

cd $KAPPA_HOME/ramdisk
echo "Packaging Ramdisk"
rm kappa-ka-ramdisk.img
find . | grep -v .git | cpio --quiet -H newc -o | gzip  > kappa-ka-ramdisk.img
cd $KAPPA_HOME/bootimg 
echo "Making image $1"
mkbootimg --kernel ../arch/arm/boot/zImage --ramdisk ../kappa-ka-ramdisk.img --base 0x00200000 -o $1
ls -alrt $1
echo "Finished"


